version: '3'

services:
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    # ports:
    #   - "3307:3306"

  
  # crud_pma:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: pma

  #   environment:
  #     PMA_HOST: db
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1

  #   ports:
  #     - 20002:80


  web:
    # build:
      # context: .
      # dockerfile: Dockerfile
    image: pedrocortez/todo-app
    container_name: web
    depends_on:
      - db
    ports:
      - 5000:5000
volumes:
  db_data: